### ISSUE TITLE
support of enum in raml for query parameters

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#110]
Hi,
Another cool thing to support could be the enum type of query parameters like:
```
  - orderable:
      queryParameters:
        order:
          description: Order
          enum: [desc, asc]
```
The java generated code take it as simple string without validation.
The issue can be linked to #108.

**Comment by stojsavljevic** [comment]
Hi @mehdijouan,

sorry for being so late.

Workaround for this is to define a data type like this:
```
types: 
  Order:
    type: string
    description: Order
    enum: [desc, asc]
```
and then you define `queryParameters`:
```
queryParameters: 
      order: Order
```
and you'll get code like this:
```
    public ResponseEntity<?> getOrder(
        @RequestParam
        Order order);
```
where `Order` is `enum`.

Does that work for you?
