### ISSUE TITLE
Reusing enums causing JClassAlreadyExistsException

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#137]
Example:
```
types:
  MyEnum:
    type: string #tried also without this line
    enum: [ "X", "Y" ]
  TestItem1:
    type: object
    properties:
      cType:
        type: MyEnum
  TestItem2:
    type: object
    properties:
      cType:
        type: MyEnum
```
