### ISSUE TITLE
Default value for the type property not parsed

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#144]
Type definition:
```
types:
  TestResource:
    type: object
    properties:
      active: 
        type: boolean
        default: false
```

Generated class:
```
public class PayeeAccountResource implements Serializable
{
    final static long serialVersionUID = 1285446397945918039L;

    @NotNull
    private Boolean active;
}
```

Expected behavior:
```
public class PayeeAccountResource implements Serializable
{
    final static long serialVersionUID = 1285446397945918039L;

    @NotNull
    private Boolean active = false;
}
```
