### ISSUE TITLE
Type must be defined if library is used

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#147]
If data types are defined within the library type must be defined in the main RAML file (which should not be a case).

Example:
```
Library file:
#%RAML 1.0 Library

usage: Some example library.

types:
  TestResource:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
```

```
api.raml
#%RAML 1.0
  title: test-api
  version: v1.0
  baseUri: /test-api

  resourceTypes:
    standard: !include resourceTypes/standard.raml

  uses:
    TestLib: libraries/test-lib.raml
```

This is not enough, if you have to use `TestResource` then you have to add `types` section too.

```
types:
  TestResource: TestLib.TestResource
```
