### ISSUE TITLE
Issue with object without properties

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#172]
When generating code from raml like this:
```
#%RAML 1.0
title: Error Example
baseUri: /
types:
  EventCreate:
    type: object
    displayName: Event Creation Data Type
    properties:
      eventName:
        type: string
        description: "The Name of the event"
      eventPayload:
        type: object
        description: "The event payload"
/events:
  post:
    body:
      application/json:
        type: EventCreate
```

`EventPayload` pojo gets generated with two empty constructors so compilation fails.
