### ISSUE TITLE
Support form parameters (part of mime type)

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#176]
Currently, form parameters (as part of mime type) are not supported.
When trying to generate code from raml like this:
```
#%RAML 1.0

title: Support form parameters please
 
/mimeTest:
  post:
    body: 
      application/x-www-form-urlencoded:
        properties: 
          form_string_param: string
          form_int_param: integer
```

`UnsupportedOperationException` is thrown.
