### ISSUE TITLE
displayName overrides real name when generating code

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#177]
When generating code from raml that has `displayName` set on `headers`, `queryParameters` or `uriParameters`, `displayName` will be used in generated code instead of real parameter name.

Example raml:
```
#%RAML 1.0

description: Showcase for bug with displayName
title: displayName bug

/a_resource:
  get:
    headers:
      header_string_param:
         type: string
         displayName: headerStrDisplayName
```

will, for example, generate endpoint like this:
```
@RequestMapping(value = "", method = RequestMethod.GET)
public ResponseEntity<?> getAResource(
	@RequestHeader(name = "headerStrDisplayName")
	String headerStrDisplayName) {
	return this.aResourceControllerDelegate.getAResource(headerStrDisplayName);
}
```
