### ISSUE TITLE
@Valid not added to query parameters

### ISSUE THREAD

**Issue by yuranos** [phoenixnap/springmvc-raml-plugin#193]
If I have a raml like:
```
    get:
      description: Get the booking details with `bookingRef = {bookingRef}`
      queryParameters:
        siteKey : SiteKey
```
A controller will not add @Valid to SiteKey method argument.

**Comment by stojsavljevic** [comment]
Hi @yuranos 

So, you're sending complex object (_SiteKey_) as a request parameter?
How does that look like?

@Valid annotation is added when object is submitted through request body.
So, in your example that will be something like:
```
post:
   description: Get the booking details with `bookingRef = {bookingRef}`
   body: 
      application/json:
        type: SiteKey
```
