### ISSUE TITLE
Problem with arrays as queryParameters

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#204]
When generating code from:
```
/test:
    post:
      queryParameters:
        locationIds:
          type: array
          items: integer
```
I get this:
```
public ResponseEntity<?> createCommonsThing(array locationIds);
```
`array` obviously doesn't compile.
