### ISSUE TITLE
Problem with data type properties defined as array

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#210]
If we define data type like this:
```
types:
  User:
    properties:
      lastName: string
      nickNames: string[]
```
POJO with following field is generated:
```
private List<string[]> nickNames = new ArrayList<string[]>();
```

However, defining array like this works:
```
types:
  User:
    properties:
      lastName: string
      nickNames:
        type: array
        items: string 
```
