### ISSUE TITLE
@Valid annotation is not generated for properties with complex object type

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#224]
If you have following situation:

```
#%RAML 1.0 Library

types:
  Item:
    type: object
    properties: 
      id: integer
      name: string 
  Product:
    type: object
    properties: 
      id: number
      name: string
      items:
        type: Item[]  
```

`@Valid` annotation is not generated on `Product -> items` property. As consequence, default validation is not triggered.

Please let me know if you need additional details.
