### ISSUE TITLE
@Delete does not generate body parameter

### ISSUE THREAD

**Issue by alvarovila-ck** [phoenixnap/springmvc-raml-plugin#235]
Using this definition
```
delete:
        body:
          application/json:
            type: <<some complex type here>>
```

the expected result was
```
@RequestMapping(value = "/", method = RequestMethod.DELETE)
    public ResponseEntity<?> delete(ComplexObject body);
```

but it was 
```
@RequestMapping(value = "/", method = RequestMethod.DELETE)
    public ResponseEntity<?> delete();
```

the goal is to send a list of ids to perform a batch deleted. Maybe my RAML definition is wrong?
