### ISSUE TITLE
Option to skip type's attribute from toString

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#247]
In some cases certain attribute of data type might be sensitive so it should be excluded from `toString` method.

The only way to support this is to introduce custom annotation on type declaration that will mark fields as sensitive:
```
annotationTypes: 
  isSensitive:
    type: boolean
    allowedTargets: TypeDeclaration

types:
  User: # kind can equal `User`; default value for `discriminatorValue`
    type: object
    properties:
      userId:
        type: integer
      salary:
        type: integer
        (isSensitive): true
```

So, the plugin will recognize annotation called `isSensitive` and will skip annotated attribute from `toString` method.
