### ISSUE TITLE
Inherited properties not respected

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#248]
Generated POJOs should properly reflect properties even in case of data type inheritance.

Example:
```
types: 
  Person:
    type: object
    properties: 
      firstName:
        type: string
        maxLength: 5
  User:
    type: Person
    properties: 
      firstName:
        default: Alex
        minLength: 3
        pattern: ^[a-zA-Z]+$
        description: Some property description
        example: Aleks
```

Expected result is `User.java` that handles its own `default`, `minLength` and `pattern` properties.
`Person.java` should define `firstName` and handle `maxLength` validation.
