### ISSUE TITLE
Method names for DELETE are not self-explanatory

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#261]
For raml:
```
/test/{testId}:
  uriParameters:
      testId: integer
  delete:
```
generated method will be `deleteByTestId` which is not self-explanatory enough.
It would be better to use resource name (`/test` in this example) and generate `deleteTestByTestId` name.
