### ISSUE TITLE
@Valid annotations added on same getter in both parent and child objects lead to exception

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#265]
In case we have something like this:
```
types: 
  Addres: 
    type: object
    properties: 
      city: string
      street: string
      houseNo: string
  Parent: 
    type: object
    properties: 
      address: Addres
  Child: 
    type: Parent
```
the plugin will generate `getAddres` method in both `Parent` and `Child` with `@Valid` annotation (if validation is used). But when validating `Child` object exception is thrown:
```
javax.validation.ConstraintDeclarationException: HV000131: A method return value must not be marked for cascaded validation more than once in a class hierarchy, but the following two methods are marked as such: ...
```
