### ISSUE TITLE
Enums create String.java source file which is confusing

### ISSUE THREAD

**Issue by techpavan** [phoenixnap/springmvc-raml-plugin#282]
I have a project where RAML defines some parameters that accept a string array whose values are confined in an enum. When code is generated for this API, it generates a class String.java which adds confusion during development.

Below is the link to reproducer.
https://github.com/techpavan/springmvc-raml-plugin-issues/tree/master/1

**Comment by stojsavljevic** [comment]
Hi @techpavan 

so you have `Bus` object defined like this:
```
type: object
properties:
  metadata:
    type: array
    items:
        enum: [ac, multi-axle, reading-light, sleeper]
```
why don't you define separate enum object like this:
```
MyEnum:
  type: string
  enum: [ac, multi-axle, reading-light, sleeper]
```
and use it like this in `Bus` declaration:
```
type: object
properties:
  metadata:
    type: array
    items: MyEnum
```
That way you'll get `MyEnum.java` generated.
