### ISSUE TITLE
Import Statement for BigDecimal/BigInteger not generated for request body

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#288]
For `useBigDecimals=true` (`useBigIntegers=true`) and this raml:
```
#%RAML 1.0
title: Import Statement for BigDecimal not generated for request body
version: 1.0

/test:
  post:
    body: 
      application/json:
        type: number
        format: long
```
import statement for `BigDecimal` (`BigInteger`) is not generated.
This happens for all rules.
