### ISSUE TITLE
Union type support broken

### ISSUE THREAD

**Issue by Phil-Ba** [phoenixnap/springmvc-raml-plugin#289]
Currently trying to use union types leads to a NullPointerException:

> Caused by: java.lang.NullPointerException
> 	at com.phoenixnap.oss.ramlplugin.raml2code.interpreters.UnionTypeInterpreter.getParent(UnionTypeInterpreter.java:69)
> 	at com.phoenixnap.oss.ramlplugin.raml2code.interpreters.UnionTypeInterpreter.interpret(UnionTypeInterpreter.java:115)
> 	at com.phoenixnap.oss.ramlplugin.raml2code.helpers.RamlTypeHelper.mapTypeToPojo(RamlTypeHelper.java:100)
> 	at com.phoenixnap.oss.ramlplugin.raml2code.plugin.SpringMvcEndpointGeneratorMojo.generateUnreferencedObjects(Spring

Example:
```yml
types:
  boolOrString:
    displayName: test
    type: string | boolean
```

**Comment by Phil-Ba** [comment]
Ok, problem seems to occur when description is missing.
This seems to be working
```yaml
types:
  boolOrString:
    description: test
    type: string | boolean
```
