### ISSUE TITLE
Query parameter enums are generated as Strings

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#292]
raml like this:
```
#%RAML 1.0
title: Query parameter enums are generated as Strings #291

/bus:
  get:
    queryParameters:
      brandName:
        type: string
        enum: [Volvo, Scania]
```
will generated method where `brandName` is a `String`.
`BrandName` enum will be generated but not referenced.

If `brandName` is a data type enum will be referenced as it should be.
