### ISSUE TITLE
Plugin is not adding BaseUriParameters in the method signatures

### ISSUE THREAD

**Issue by manikmagar** [phoenixnap/springmvc-raml-plugin#301]
Given this RAML - 

```
#%RAML 1.0
title: Amazon S3 REST API
version: 1
baseUri: /v1/{somekey}
baseUriParameters:
  somekey:
    description: The name of the bucket
    type: string

/common:
  /list:
    get:
```

Plugin generated following controller with 2.0.5 version -

```
@RestController
@Validated
@RequestMapping("/v1/{somekey}/common/list")
public interface ListController {

    @RequestMapping(value = "", method = RequestMethod.GET)
    public ResponseEntity<?> getObject(
        @RequestHeader
        HttpHeaders httpHeaders);

}
```
As seen in the method signature, it is missing the injection of `somekey` path variable.
