### ISSUE TITLE
[raml to code] defaultValue is not generated

### ISSUE THREAD

**Issue by stojsavljevic** [phoenixnap/springmvc-raml-plugin#99]
When generating code from raml - `defaultValue` is not set for `@RequestParam` and `@RequestHeader`.
So, if we have defaults set in raml file like this:
```
#%RAML 0.8
...
/someendpoint:
  get:
    description: Get all objects
    queryParameters:
      optionalQueryParam:
        type: string
        default: "someDefault"
    headers:
      X-Optional-Header:
        type: integer
        required: false
        default: 3
```
I would expect to get something like:
```
@RequestParam(required = false, defaultValue = "someDefault") String optionalQueryParam,
@RequestHeader(name = "X-Optional-Header", required = false, defaultValue = "3") Long xOptionalHeader
```
